# Generated by Django 4.0.4 on 2022-05-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_sobre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('noticia', models.CharField(max_length=50)),
                ('imagem', models.ImageField(null=True, upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='sobre',
            name='imagem',
        ),
    ]
