# Generated by Django 4.0.4 on 2022-05-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_cadeiras_id_alter_post_id_alter_projetos_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='noticia',
            field=models.CharField(max_length=50),
        ),
    ]
