# Generated by Django 4.0.4 on 2022-06-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_web_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tfc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autores', models.CharField(max_length=500)),
                ('orientadores', models.CharField(max_length=500)),
                ('ano', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.CharField(max_length=500)),
                ('imagem', models.ImageField(null=True, upload_to='media/')),
                ('relatorio', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='web',
            name='noticia',
            field=models.CharField(max_length=1000),
        ),
    ]
